---
base:
  data_dir: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0"
  working_dir: ~
  role: validator
  waypoint:
    from_config: "0:3493de04819edf0c2f2a5659cd4d1af68b82fe08ba10357176980e418c7d42f4"
consensus:
  max_sending_block_txns: 2500
  max_sending_block_txns_quorum_store_override: 4000
  max_sending_block_bytes: 614400
  max_sending_block_bytes_quorum_store_override: 5242880
  max_receiving_block_txns: 10000
  max_receiving_block_txns_quorum_store_override: 8000
  max_receiving_block_bytes: 3145728
  max_receiving_block_bytes_quorum_store_override: 6291456
  max_pruned_blocks_in_mem: 100
  mempool_executed_txn_timeout_ms: 1000
  mempool_txn_pull_timeout_ms: 1000
  round_initial_timeout_ms: 1500
  round_timeout_backoff_exponent_base: 1.2
  round_timeout_backoff_max_exponent: 6
  safety_rules:
    backend:
      type: on_disk_storage
      path: secure_storage.json
      namespace: ~
    logger:
      chan_size: 10000
      enable_backtrace: false
      is_async: true
      level: INFO
      console_port: 6669
      enable_telemetry_remote_log: true
      enable_telemetry_flush: true
      telemetry_level: ERROR
    service:
      type: thread
    test: ~
    network_timeout_ms: 30000
    enable_cached_safety_data: true
    initial_safety_rules_config:
      from_file:
        identity_blob_path: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0\\validator-identity.yaml"
        waypoint:
          from_config: "0:3493de04819edf0c2f2a5659cd4d1af68b82fe08ba10357176980e418c7d42f4"
  sync_only: false
  channel_size: 30
  quorum_store_pull_timeout_ms: 1000
  quorum_store_poll_count: 10
  intra_consensus_channel_buffer_size: 10
  quorum_store_configs:
    channel_size: 1000
    proof_timeout_ms: 10000
    batch_request_num_peers: 2
    mempool_pulling_interval: 250
    end_batch_ms: 10
    max_batch_bytes: 4194304
    batch_request_timeout_ms: 10000
    batch_expiry_round_gap_when_init: 100
    batch_expiry_round_gap_behind_latest_certified: 500
    batch_expiry_round_gap_beyond_latest_certified: 500
    batch_expiry_grace_rounds: 5
    memory_quota: 100000000
    db_quota: 10000000000
    mempool_txn_pull_max_bytes: 4194304
    back_pressure:
      backlog_txn_limit_count: 16000
      decrease_duration_ms: 1000
      increase_duration_ms: 1000
      decrease_fraction: 0.5
      dynamic_min_batch_count: 40
      dynamic_max_batch_count: 500
    num_workers_for_remote_fragments: 10
  window_for_chain_health: 100
  chain_health_backoff:
    - backoff_if_below_participating_voting_power_percentage: 80
      max_sending_block_txns_override: 2000
      max_sending_block_bytes_override: 512000
    - backoff_if_below_participating_voting_power_percentage: 77
      max_sending_block_txns_override: 1000
      max_sending_block_bytes_override: 256000
    - backoff_if_below_participating_voting_power_percentage: 75
      max_sending_block_txns_override: 400
      max_sending_block_bytes_override: 102400
    - backoff_if_below_participating_voting_power_percentage: 72
      max_sending_block_txns_override: 200
      max_sending_block_bytes_override: 51200
    - backoff_if_below_participating_voting_power_percentage: 69
      max_sending_block_txns_override: 100
      max_sending_block_bytes_override: 25600
execution:
  genesis_file_location: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0\\genesis.blob"
  concurrency_level: 1
  num_proof_reading_threads: 1
  paranoid_type_verification: true
  paranoid_hot_potato_verification: true
  processed_transactions_detailed_counters: false
full_node_networks:
  - max_connection_delay_ms: 60000
    connection_backoff_base: 2
    connectivity_check_interval_ms: 5000
    network_channel_size: 1024
    max_concurrent_network_reqs: 100
    discovery_method: onchain
    discovery_methods: []
    identity:
      type: from_file
      path: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0\\vfn-identity.yaml"
    listen_address: /ip4/0.0.0.0/tcp/6181
    mutual_authentication: false
    network_id: public
    runtime_threads: ~
    inbound_rx_buffer_size_bytes: 3145728
    inbound_tx_buffer_size_bytes: 524288
    outbound_rx_buffer_size_bytes: 3145728
    outbound_tx_buffer_size_bytes: 1048576
    seed_addrs: {}
    seeds: {}
    max_frame_size: 4194304
    enable_proxy_protocol: false
    ping_interval_ms: 10000
    ping_timeout_ms: 20000
    ping_failures_tolerated: 3
    max_outbound_connections: 0
    max_inbound_connections: 30
    inbound_rate_limit_config: ~
    outbound_rate_limit_config: ~
    max_message_size: 67108864
  - max_connection_delay_ms: 60000
    connection_backoff_base: 2
    connectivity_check_interval_ms: 5000
    network_channel_size: 1024
    max_concurrent_network_reqs: 100
    discovery_method: none
    discovery_methods: []
    identity:
      type: from_file
      path: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0\\vfn-identity.yaml"
    listen_address: /ip4/0.0.0.0/tcp/50966
    mutual_authentication: false
    network_id:
      private: vfn
    runtime_threads: ~
    inbound_rx_buffer_size_bytes: 3145728
    inbound_tx_buffer_size_bytes: 524288
    outbound_rx_buffer_size_bytes: 3145728
    outbound_tx_buffer_size_bytes: 1048576
    seed_addrs: {}
    seeds: {}
    max_frame_size: 4194304
    enable_proxy_protocol: false
    ping_interval_ms: 10000
    ping_timeout_ms: 20000
    ping_failures_tolerated: 3
    max_outbound_connections: 0
    max_inbound_connections: 30
    inbound_rate_limit_config: ~
    outbound_rate_limit_config: ~
    max_message_size: 67108864
inspection_service:
  address: 0.0.0.0
  port: 9101
  expose_configuration: false
  expose_system_information: true
logger:
  chan_size: 10000
  enable_backtrace: false
  is_async: true
  level: DEBUG
  console_port: 6669
  enable_telemetry_remote_log: true
  enable_telemetry_flush: true
  telemetry_level: ERROR
mempool:
  capacity: 2000000
  capacity_bytes: 2147483648
  capacity_per_user: 100
  default_failovers: 3
  max_broadcasts_per_peer: 1
  mempool_snapshot_interval_secs: 180
  shared_mempool_ack_timeout_ms: 2000
  shared_mempool_backoff_interval_ms: 30000
  shared_mempool_batch_size: 100
  shared_mempool_max_batch_bytes: 64880640
  shared_mempool_max_concurrent_inbound_syncs: 1
  shared_mempool_tick_interval_ms: 50
  system_transaction_timeout_secs: 600
  system_transaction_gc_interval_ms: 60000
  broadcast_buckets:
    - 0
    - 150
    - 300
    - 500
    - 1000
    - 3000
    - 5000
    - 10000
    - 100000
    - 1000000
metrics: {}
peer_monitoring_service:
  max_concurrent_requests: 1
  max_network_channel_size: 1000
api:
  enabled: true
  address: "0.0.0.0:8080"
  failpoints_enabled: false
  json_output_enabled: true
  bcs_output_enabled: true
  encode_submission_enabled: true
  transaction_submission_enabled: true
  transaction_simulation_enabled: true
  max_submit_transaction_batch_size: 10
  max_transactions_page_size: 100
  max_events_page_size: 100
  max_account_resources_page_size: 9999
  max_account_modules_page_size: 9999
  max_gas_view_function: 2000000
state_sync:
  data_streaming_service:
    global_summary_refresh_interval_ms: 50
    max_concurrent_requests: 3
    max_concurrent_state_requests: 6
    max_data_stream_channel_sizes: 300
    max_request_retry: 5
    max_notification_id_mappings: 300
    progress_check_interval_ms: 100
  aptos_data_client:
    max_num_in_flight_priority_polls: 10
    max_num_in_flight_regular_polls: 10
    max_num_output_reductions: 0
    max_response_timeout_ms: 60000
    response_timeout_ms: 10000
    subscription_timeout_ms: 5000
    summary_poll_interval_ms: 200
    use_compression: true
  state_sync_driver:
    bootstrapping_mode: ApplyTransactionOutputsFromGenesis
    commit_notification_timeout_ms: 5000
    continuous_syncing_mode: ApplyTransactionOutputs
    enable_auto_bootstrapping: true
    fallback_to_output_syncing_secs: 180
    progress_check_interval_ms: 100
    max_connection_deadline_secs: 10
    max_consecutive_stream_notifications: 10
    max_num_stream_timeouts: 12
    max_pending_data_chunks: 100
    max_stream_wait_time_ms: 5000
    num_versions_to_skip_snapshot_sync: 100000000
  storage_service:
    max_concurrent_requests: 4000
    max_epoch_chunk_size: 200
    max_lru_cache_size: 500
    max_network_channel_size: 4000
    max_network_chunk_bytes: 4194304
    max_state_chunk_size: 4000
    max_subscription_period_ms: 5000
    max_transaction_chunk_size: 2000
    max_transaction_output_chunk_size: 1000
    storage_summary_refresh_interval_ms: 50
indexer_grpc:
  enabled: false
indexer:
  enabled: false
storage:
  backup_service_address: "127.0.0.1:6186"
  dir: db
  storage_pruner_config:
    ledger_pruner_config:
      enable: true
      prune_window: 150000000
      batch_size: 500
      user_pruning_window_offset: 200000
    state_merkle_pruner_config:
      enable: true
      prune_window: 1000000
      batch_size: 1000
    epoch_snapshot_pruner_config:
      enable: true
      prune_window: 80000000
      batch_size: 1000
  buffered_state_target_items: 100000
  max_num_nodes_per_lru_cache_shard: 8192
  rocksdb_configs:
    ledger_db_config:
      max_open_files: 5000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
    state_merkle_db_config:
      max_open_files: 5000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
    use_state_kv_db: false
    state_kv_db_config:
      max_open_files: 5000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
    index_db_config:
      max_open_files: 1000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
  enable_indexer: false
test: ~
validator_network:
  max_connection_delay_ms: 10000
  connection_backoff_base: 2
  connectivity_check_interval_ms: 10000
  network_channel_size: 1024
  max_concurrent_network_reqs: 1
  discovery_method: onchain
  discovery_methods: []
  identity:
    type: from_file
    path: "\\\\?\\D:\\move\\aptosEx\\.aptos\\testnet\\0\\validator-identity.yaml"
  listen_address: /ip4/0.0.0.0/tcp/6180
  mutual_authentication: true
  network_id: validator
  runtime_threads: 1
  inbound_rx_buffer_size_bytes: 3145728
  inbound_tx_buffer_size_bytes: 524288
  outbound_rx_buffer_size_bytes: 3145728
  outbound_tx_buffer_size_bytes: 1048576
  seed_addrs: {}
  seeds: {}
  max_frame_size: 4194304
  enable_proxy_protocol: false
  ping_interval_ms: 10000
  ping_timeout_ms: 20000
  ping_failures_tolerated: 3
  max_outbound_connections: 4
  max_inbound_connections: 30
  inbound_rate_limit_config: ~
  outbound_rate_limit_config: ~
  max_message_size: 67108864
failpoints: ~
